# Generated by Django 4.0.3 on 2022-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
