# Generated by Django 4.0.3 on 2022-06-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkpage', '0003_alter_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
